server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codearena?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ""
  mail:
    host: smtp.gmail.com
    port: 587
    username: islemazzouz04@gmail.com
    password: ycsm qcyo tqfk hlbd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-70do2fpg2iw11ckn.us.auth0.com/
          jwk-set-uri: https://dev-70do2fpg2iw11ckn.us.auth0.com/.well-known/jwks.json

keycloak:
  realm: code-arena
  client-id: code-arena-backend
  server-url: http://localhost:8081

app:
  cors:
    allowed-origins:
      - http://localhost:4200
  shop:
    admin-email: islemazzouz04@gmail.com

    stripe:
      secret-key: ${STRIPE_SECRET_KEY:your-stripe-secret-key-here}
      publishable-key: pk_test_51TFMdY0mrwK4eA2C92xU22HoJGLjz7LxnNVuGHuvrjKKeJbWXqdThqoAFRzGlQ6b1sUGPpx60S1hHrT54I3SkXeC00aMOhTVTN


