sonar.projectKey=codearena-frontend
sonar.projectName=CodeArena Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts

sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/code-arena-frontend/lcov.info