sonar.projectKey=CodeArena_Frontend_Manual
sonar.projectName=Code Arena Frontend
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io
sonar.organization=h1000rekik

# Path to the source code
sonar.sources=src
# Exclude test files, node_modules, and environments from source code analysis
sonar.exclusions=**/node_modules/**,src/**/*.spec.ts,src/environments/**,src/assets/**

# Path to the test code
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

# Linter and Coverage reports
# For Angular, typically using karma-coverage / istanbul
sonar.javascript.lcov.reportPaths=coverage/code-arena-frontend/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
